name: chat_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  cloud_firestore: ^4.8.1
  firebase_storage: ^11.3.1
  shared_preferences: ^2.1.2
  flutter_screenutil: ^5.8.4
  google_fonts: ^6.1.0
  provider: any
  localization: any
  emoji_picker_flutter: any
  firebase_database: any
  flutter_bloc: ^8.1.3
  image_picker: ^1.0.4
  fancy_shimmer_image: ^2.0.3


dev_dependencies:
  lint: ^2.2.0
  flutter_test:
    sdk: flutter
  intl: any
  flutter_lints: ^3.0.1

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/images/
    - lib/l10n/
