name: chat_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.6.3
  firebase_core: ^2.30.0
  cloud_firestore: ^4.8.1
  firebase_storage: ^11.3.1
  shared_preferences: ^2.1.2
  flutter_screenutil: ^5.8.4
  google_fonts: ^6.1.0
  provider: any
  localization: 2.1.1
  emoji_picker_flutter: any
  firebase_database: any
  flutter_bloc: ^8.1.3
  image_picker: ^1.0.4
  fancy_shimmer_image: ^2.0.3
  firebase_messaging: ^14.8.1
  http: ^1.2.1
  firebase_analytics: ^10.10.1
  permission_handler: ^11.3.1
  country_picker: ^2.0.25
  shorebird_code_push: ^1.1.3
  package_info_plus: ^7.0.0
  url_launcher: ^6.2.6
  audioplayers: ^6.0.0
  device_preview: ^1.1.0
  record: ^5.0.5
  path_provider: ^2.1.3
  image: ^4.1.7
  video_player: ^2.8.6
  video_thumbnail: ^0.5.3
  photo_view: ^0.15.0
  rxdart: ^0.27.7
  image_cropper: ^5.0.1
  intl: 0.19.0
  flutter_audio_waveforms: ^1.2.1+8
  fluttertoast: ^8.0.9
  image_gallery_saver: ^2.0.3
  file_picker: ^8.0.3

dev_dependencies:
  lint: ^2.2.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1


flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/images/
    - assets/audios/
    - lib/l10n/
    - shorebird.yaml
