name: chat_app
description: Chat Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.6.3
  firebase_core: ^2.30.0
  cloud_firestore: ^4.8.1
  firebase_storage: ^11.3.1
  shared_preferences: ^2.1.2
  flutter_screenutil: ^5.8.4
  google_fonts: any
  provider: any
  localization: any
  emoji_picker_flutter: any
  firebase_database: any
  flutter_bloc: ^8.1.3
  image_picker: ^1.0.4
  fancy_shimmer_image: ^2.0.3
  firebase_messaging: ^14.8.1
  http: ^1.2.1
  permission_handler: ^11.3.1
  country_picker: any
  shorebird_code_push: ^1.1.3
  package_info_plus: any
  url_launcher: ^6.2.6
  audioplayers: ^6.0.0
  record: ^5.0.5
  image: ^4.1.7
  video_player: ^2.8.6
  video_thumbnail: ^0.5.3
  photo_view: ^0.15.0
  rxdart: ^0.27.7
  image_cropper: ^5.0.1
  intl: any
  fluttertoast: ^8.0.9
  image_gallery_saver: ^2.0.3
  file_picker: any
  path_provider: ^2.1.3
  equatable: ^2.0.5
  flutter_reaction_button: ^3.0.0+3
#  flutter_ffmpeg: ^0.4.0

dev_dependencies:
  lint: ^2.2.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1


flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/images/
    - assets/audios/
    - lib/l10n/
    - shorebird.yaml
